/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Files;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Pasindu
 */
public class Add_UserScreen extends javax.swing.JFrame {

String newpath;
    /**
     * Creates new form Add_UserScreen
     */
    
    public Add_UserScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        combo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        WardAssignedJtxt = new javax.swing.JLabel();
        wardNamesComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 545));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 545));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cornerstone", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add A New User ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 250, 30));

        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("NIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setText("Designation");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 130, 150));

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        FName.setPreferredSize(new java.awt.Dimension(5, 20));
        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });
        jPanel1.add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, 30));
        jPanel1.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 290, -1));
        jPanel1.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 290, -1));

        buttonGroup1.add(MaleButton);
        MaleButton.setText("Male");
        jPanel1.add(MaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 50, -1));

        buttonGroup1.add(FemaleButton);
        FemaleButton.setText("Female");
        jPanel1.add(FemaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nurse", "doctor", "labtechnician", "administrator" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jLabel9.setText("Date of Birth");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 110, -1));

        jLabel10.setText("contact");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 290, -1));

        jLabel11.setText("Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jAddress.setColumns(20);
        jAddress.setRows(5);
        jScrollPane1.setViewportView(jAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 280, 60));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 370, 20));

        WardAssignedJtxt.setText("Assigned Ward");
        jPanel1.add(WardAssignedJtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 20));

        wardNamesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maternity", "Pediatrics", "Oncology", "Gynecologist", "General surgery" }));
        jPanel1.add(wardNamesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(447, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {        
            //ResultSet RS = dbcon.search("SELECT * FROM "+table+ "WHERE fid='"+fid.getText()+"'");
            JFileChooser jc = new JFileChooser(new File("E:/SCS Second Year/SCS 2104 Programming 3/Assignments/Take_Home_Assignment2017/Meta data for sample data sets"));
            //C:/Users/Pasindu/Pictures
            int x = jc.showOpenDialog(this);
            if (x == jc.APPROVE_OPTION) {
                File f1 = jc.getSelectedFile();
                String path = f1.getAbsolutePath();
                newpath = path.replace("\\", "/");
                f1=new File(newpath);
                Image i = ImageIO.read(f1);
                i = i.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
                img.setIcon(new  ImageIcon(i));
                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Save into tables here
        
        String table = combo.getSelectedItem().toString();
        int wardNum = -1; //This value is checked in Create_UName_Pword screen and validated
        if (table.equals("nurse")) {
            /*Ward numbers 
                0 - Maternity, 
                1 - Pediatrics,
                2 - Oncology,
                3 - Gynecologist,
                4 - General surgery
            */
            wardNum =  wardNamesComboBox.getSelectedIndex();
        }
        String firstName = FName.getText();
        String lastName = LName.getText();        
        String Gender;
        String Desig = combo.getSelectedItem().toString();
        String IDNum = NIC.getText();
        String dateOB = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        if (MaleButton.isSelected()) {
            Gender = "M";
        }else{
            Gender = "F";
        }
        String contactNum = contact.getText();
        String address = jAddress.getText();
        
    try {        
        dbcon.IUD("INSERT INTO employee (FName, LName, DOB, gender, NIC, address, contact, imgPath) VALUES ('"+firstName+"','"+lastName+"','"+dateOB+"','"+Gender+"', '"+IDNum+"', '"+address+"', '"+contactNum+"', '"+newpath+"')"); //This query is ok
        
        // create a jframe
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
        
        // show a joptionpane dialog using showMessageDialog
        JOptionPane.showMessageDialog(frame,
            "Successfully added as an employee","Query Executed",JOptionPane.INFORMATION_MESSAGE);
        
        ResetFields();
        
        create_UName_Pword newUNameandPass = new create_UName_Pword(IDNum, table, wardNum);
        newUNameandPass.setVisible(true);
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        combo.setSelectedIndex(0);
        FName.setText(null);
        LName.setText(null);
        NIC.setText(null);
        MaleButton.setSelected(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        //When clicked on the combo box event is other combo box pops up or not
        if (combo.getSelectedIndex() != 0) {
            WardAssignedJtxt.setEnabled(false);
            wardNamesComboBox.setEnabled(false);
        }else{
            WardAssignedJtxt.setEnabled(true);
            wardNamesComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_UserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FName;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JTextField LName;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JTextField NIC;
    private javax.swing.JLabel WardAssignedJtxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel img;
    private javax.swing.JTextArea jAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox wardNamesComboBox;
    // End of variables declaration//GEN-END:variables

    private void ResetFields() {
        combo.setSelectedIndex(0);
        FName.setText(null);
        LName.setText(null);
        NIC.setText(null);
        contact.setText(null);
        jAddress.setText(null);
        img.setIcon(null);
    }
}
