/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Files;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Pasindu
 */
public class Employee_Payments extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Payments
     */
    private String NICNum;
    private String Designation;
    private int adminempId;
    private int employeeId;
    private long attendeddDays;
    private String checkedPerson;
    public Employee_Payments(int adminempId) {
        this.adminempId = adminempId;
        initComponents();
        showtime();
    }
    
    void showtime() {
        new javax.swing.Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss:a");
                SimpleDateFormat sdf2 = new SimpleDateFormat("yy-MM-dd");
                String tt = sdf.format(d);
                String dt = sdf2.format(d);
                time.setText(tt);
                date.setText(dt);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NICText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        ToTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDesignationTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        payJText = new javax.swing.JTextField();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkedPrson = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cornerstone", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 250, -1));
        jPanel1.add(NICText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, 20));

        jLabel2.setText("NIC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, -1));

        jLabel3.setText("From");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-d");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel4.setText("To");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        jPanel1.add(ToTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 100, -1));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel6.setText("Designation");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jDesignationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 210, -1));

        jLabel9.setText("Payment");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel1.add(payJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, -1));

        time.setText("Time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 90, -1));

        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, -1));

        jLabel7.setText("Checked By");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(checkedPrson, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, 20));

        jButton2.setText("Record Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        jButton5.setText("Tabulate");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 259, 60, 20));
        jPanel1.add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(431, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Using Jaspersoft - iReport generate a report
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");

        JOptionPane.showMessageDialog(frame,
            "Jaspersoft iReport feature will be added soon",
            "updates will come",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NICNum = NICText.getText();
        
        try {
            ResultSet RS = dbcon.search("SELECT * FROM employee WHERE NIC='"+NICNum +"'");
            if (RS.next()) {
                employeeId = RS.getInt("empId");
                NameTxt.setText(RS.getString("FName") + " " + RS.getString("LName"));            
                ToTxt.setText(time.getText());
                int empId = RS.getInt("empId");
                /*Amount due has to be calculated from the difference of dates between from and to + designation has to be considered*/
                /*Finding designation is done through a set of search queries executed using dbcon file*/
                ResultSet RSDoc = dbcon.search("SELECT docId FROM doctor WHERE empId="+empId+"");
                ResultSet RSNurse = dbcon.search("SELECT nurseId FROM nurse WHERE empId="+empId+"");
                ResultSet RSLT = dbcon.search("SELECT labTechId FROM labtechnician WHERE empId="+empId+"");

                if(RSDoc.next()){
                    Designation = "Doctor";
                }else if (RSNurse.next()) {
                    Designation = "Nurse";
                }else if(RSLT.next()){
                    Designation = "Lab Technician";
                }
            }else{
                errorMsg.setText("No such record found. Please recheck the NIC.");
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");

            JOptionPane.showMessageDialog(frame,
                "Something went Wrong",
                "Oops",
                JOptionPane.ERROR_MESSAGE);
        
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            //To calculate the payment
            /*
            Payment Criteria
            Doctor === 800 LKR per day
            LabTechnician === 400 LKR per day
            Nurse === 200 LKR  per day
            */
            
            String FromDate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            String Today = ToTxt.getText();
            
            attendeddDays = dateDifference(FromDate, Today);
            
            if (Designation.equals("Doctor")) {
               payJText.setText(String.valueOf((float)800.00* attendeddDays));
            }else if (Designation.equals("Nurse")) {
               payJText.setText(String.valueOf((float)200.00* attendeddDays)); 
            }else if(Designation.equals("Lab Technician")){
               payJText.setText(String.valueOf((float)400.00* attendeddDays));
            }
            
                                  
            //Sets the checkedby attribute
            ResultSet RS = dbcon.search("SELECT FName, LName FROM employee WHERE empId="+adminempId+"");
            checkedPerson = RS.getString("FName") + " " + RS.getString("LName");
            checkedPrson.setText(checkedPerson);
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            dbcon.IUD("INSERT INTO emp_payment(empId, attended_days, payment, checkedBy) VALUES ("+employeeId+", "+attendeddDays+", "+(float)Integer.parseInt(payJText.getText())+", "+checkedPerson+")");
        } catch (Exception e) {
            e.printStackTrace();
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");

            JOptionPane.showMessageDialog(frame,
                "Something went Wrong",
                "Oops",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Payments(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NICText;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField ToTxt;
    private javax.swing.JLabel checkedPrson;
    private javax.swing.JLabel date;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JTextField jDesignationTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField payJText;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
    
    private long dateDifference(String initDay, String finalDay) {
        //Calculates the date difference for two String parameters - First date and last date
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        long days = 0;
        try {
            Date date1 = myFormat.parse(initDay);
            Date date2 = myFormat.parse(finalDay);
            long diff = date2.getTime() - date1.getTime();
            days = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return days;
    }
}
