/*
 * Project is initialized here 
 */
package Java_Files;

/**
 *
 * @author Pasindu
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labAssistantButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        doctorButton = new javax.swing.JButton();
        nurseButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 503));
        jPanel1.setMinimumSize(new java.awt.Dimension(560, 503));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labAssistantButton.setText("Lab Assistant");
        labAssistantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labAssistantButtonActionPerformed(evt);
            }
        });
        jPanel1.add(labAssistantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 170, 60));

        AdminButton.setText("Administrator");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 170, 60));

        doctorButton.setText("Doctor");
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, 60));

        nurseButton.setText("Nurse");
        nurseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nurseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 170, 60));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SystemLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 560, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(586, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
        *On each button clicked a String is passed as the parameter to LoginScreen.java
        *This helps opening the following window. 
    */
    private void labAssistantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labAssistantButtonActionPerformed
        LoginScreen lALogin = new LoginScreen("labtechnician");
        lALogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labAssistantButtonActionPerformed

    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed
        LoginScreen doctorLogin = new LoginScreen("doctor");
        doctorLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctorButtonActionPerformed

    private void nurseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseButtonActionPerformed
        LoginScreen nurseLogin = new LoginScreen("nurse");
        nurseLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nurseButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        LoginScreen AdminLogin = new LoginScreen("administrator");
        AdminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton doctorButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton labAssistantButton;
    private javax.swing.JButton nurseButton;
    // End of variables declaration//GEN-END:variables
}
